// <auto-generated />
using FaktureApp.Models.Fakture;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FaktureApp.Migrations
{
    [DbContext(typeof(FakturaContext))]
    [Migration("20190125120107_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FaktureApp.Models.Fakture.Faktura", b =>
                {
                    b.Property<string>("BrojDokumenta")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BrojFakture")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<DateTime>("DatumDokumenta");

                    b.Property<double>("Ukupno");

                    b.HasKey("BrojDokumenta");

                    b.ToTable("Faktura");
                });

            modelBuilder.Entity("FaktureApp.Models.Fakture.Stavka", b =>
                {
                    b.Property<int>("RedniBroj")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BrojDokumenta");

                    b.Property<double>("Cena");

                    b.Property<double>("Kolicina");

                    b.Property<double>("Ukupno");

                    b.HasKey("RedniBroj");

                    b.HasIndex("BrojDokumenta");

                    b.ToTable("Stavka");
                });

            modelBuilder.Entity("FaktureApp.Models.Fakture.Stavka", b =>
                {
                    b.HasOne("FaktureApp.Models.Fakture.Faktura", "Faktura")
                        .WithMany()
                        .HasForeignKey("BrojDokumenta");
                });
#pragma warning restore 612, 618
        }
    }
}
