//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Proizvodi
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Morate uneti vrednost u polje")]
        public string naziv { get; set; }
        [Required(ErrorMessage = "Morate uneti vrednost u polje")]
        public string opis { get; set; }
        [Required(ErrorMessage = "Morate uneti vrednost u polje")]
        public string kategorija { get; set; }
        [Required(ErrorMessage = "Morate uneti vrednost u polje")]
        public string proizvodjac { get; set; }
        [Required(ErrorMessage = "Morate uneti vrednost u polje")]
        public string dobavljac { get; set; }
        [Required(ErrorMessage = "Morate uneti vrednost u polje")]
        public Nullable<decimal> cena { get; set; }
    }
}
