//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int CarId { get; set; }

        [Required(ErrorMessageResourceName ="ManufacturerRequired", ErrorMessageResourceType = typeof(Resources.Resource))]
        [Display(Name ="Manufacturer", ResourceType = typeof(Resources.Resource))]
        public string Make { get; set; }

        [Required(ErrorMessageResourceName = "CarModelRequired", ErrorMessageResourceType = typeof(Resources.Resource))]
        [Display(Name = "CarModel", ResourceType = typeof(Resources.Resource))]
        public string Model { get; set; }

        [Required(ErrorMessageResourceName = "ProductionYearRequired", ErrorMessageResourceType = typeof(Resources.Resource))]
        [Display(Name = "ProductionYear", ResourceType = typeof(Resources.Resource))]
        public Nullable<int> ProductionYear { get; set; }

        [Required(ErrorMessageResourceName = "EngineVolumeRequired", ErrorMessageResourceType = typeof(Resources.Resource))]
        [Display(Name = "EngineVolume", ResourceType = typeof(Resources.Resource))]
        public Nullable<int> EngineVolume { get; set; }

        [Required(ErrorMessageResourceName = "EnginePowerRequired", ErrorMessageResourceType = typeof(Resources.Resource))]
        [Display(Name = "EnginePower", ResourceType = typeof(Resources.Resource))]
        public Nullable<int> EnginePower { get; set; }

        [Required(ErrorMessageResourceName = "CarBodyRequired", ErrorMessageResourceType = typeof(Resources.Resource))]
        [Display(Name = "CarBody", ResourceType = typeof(Resources.Resource))]
        public string CarBody { get; set; }

        [Required(ErrorMessageResourceName = "DescriptionRequired", ErrorMessageResourceType = typeof(Resources.Resource))]
        [Display(Name = "Description", ResourceType = typeof(Resources.Resource))]
        public string Description { get; set; }

        [Required(ErrorMessageResourceName = "PriceRequired", ErrorMessageResourceType = typeof(Resources.Resource))]
        [Display(Name = "Price", ResourceType = typeof(Resources.Resource))]
        public Nullable<decimal> Price { get; set; }

        [Required(ErrorMessageResourceName = "ContactRequired", ErrorMessageResourceType = typeof(Resources.Resource))]
        [Display(Name = "Contact", ResourceType = typeof(Resources.Resource))]
        public string Contact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
    }
}
